export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  ORDERS: '/orders',
  EXPENSES: '/expenses',
  ADD_FUEL_EXPENSE: '/expenses/add',
  KILOMETER: '/kilometer',
  ADVANCE_PAY: '/advance-pay',
  PROFILE: '/profile',
  ROUTE_INFO: '/route-info',
  AIRPORT_DELIVERY: '/airport-delivery',
  LOCAL_ORDER_VIEW: '/local-order-view',
  AIRPORT_ORDER_VIEW: '/airport-order-view',
  LOCAL_ORDER_VIEW_INFO: '/local-order-view-info',
  AIRPORT_ORDER_VIEW_INFO: '/airport-order-view-info',
};

export const USER = {
  name: 'Bharathiraja Sekar',
  initials: 'BS',
  driverId: 'DRV-260116-0004',
  driverIdAlt: 'DRV-2021/15/0084',
  phone: '+919000867675',
  email: 'bharathiraja@gmail.com',
  address: 'ETTIYANDOR, Tamilnadu',
  city: 'ETTIYANDOR',
  state: 'Tamilnadu',
  pinCode: '636004',
  licenseNumber: '892571922810958',
  licenseExpiry: '1/8/2028',
  vehicleType: '3T VEHICLE',
  vehicleName: 'TATA ACE',
  vehicleNumber: 'TN23AR3456',
  capacity: '20',
  vehicleCondition: 'Good',
};
